### PR TITLE
Tutorials: Playwright

### LINKED ISSUE #118: Tutorials page for Playwright
Should be in **/tutorials** section https://app.testomat.io/projects/notes/test/95a1e206-documentation-structure

```
Playwright Tutorial

## Importing Playwright Tests

- import playwright tests 
  - JS tests (link to example project)
  - TypeScript tests (link to example project)
  - BDD tests 
- parametrized tests importing
- add IDs to tests

## Reporting Playwright tests

- configure reporter
- artifacts
  ( link to artifacts page)
  - videos
  - traces
     (move from Reporting page)

## Advanced 

- parallel run (link to parallel page)
```

### PR DESCRIPTION
**Pull request by maxkryvoshyya**
Not described:

1. artifacts (link to artifacts page) - **We have two pages of Test Artifacts**
2. videos - **Not enough information** 
4. parallel run (link to parallel page)  - **I didn't find it.**

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by DavertMik** [comment]
Link to artifacts https://github.com/testomatio/docs/blob/docs/src/content/docs/usage/test-artifacts.mdx

Expand on stack traces (screenshot)

Add screenshots/videos via artifacts

**Comment by DavertMik** [comment]
@AZANIR I think we may need your help here

**Comment by AZANIR** [comment]
@maxkryvoshyya please connect with me

**Comment by DavertMik** [comment]
Use this format when needed to show how commands affect the code

```diff
+ test('user should be fine @T12345678', () => {
- test('user should be fine @T12345678', () => {
  expect(user).toBe('fine');
});

```

**Pull request merged**
